/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.controlPanel;

import control.controlPanel.Actions;
import control.controlPanel.RadioID;
import javax.swing.JComponent;
import model.controlPanel.BackKey;
import model.controlPanel.PanelVisibility;
import javax.swing.JDesktopPane;
import model.BrowseImage;

/**
 *
 * @author Naveen
 */
public class ControlPanel extends javax.swing.JInternalFrame {

    /**
     * Creates new form ControlPanel
     */
    //** Class variables
    Actions actions;

    public ControlPanel() {
        initComponents();
//        initMethod();
//        onGoingMethods();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        label_heading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panel_backPanel = new javax.swing.JPanel();
        btn_back = new javax.swing.JButton();
        desktopPane_userAccount = new javax.swing.JDesktopPane();
        tabbedPane_userAccount = new javax.swing.JTabbedPane();
        panel_userAccountHome = new javax.swing.JPanel();
        desktopPane_profPicAccDet = new javax.swing.JDesktopPane();
        label_accountName = new javax.swing.JLabel();
        label_accountType = new javax.swing.JLabel();
        label_passwordDet = new javax.swing.JLabel();
        panel_changeAccountPassword = new javax.swing.JPanel();
        desktopPane_profPicChangePass = new javax.swing.JDesktopPane();
        label_accountNameChangePass = new javax.swing.JLabel();
        label_accountTypeChangePass = new javax.swing.JLabel();
        label_passwordDetChangePass = new javax.swing.JLabel();
        label_changePasswordHeader = new javax.swing.JLabel();
        label_currentPassword = new javax.swing.JLabel();
        label_newPassword = new javax.swing.JLabel();
        label_confirmPassword = new javax.swing.JLabel();
        pass_confirmPass = new javax.swing.JPasswordField();
        pass_currentPass = new javax.swing.JPasswordField();
        pass_newPass = new javax.swing.JPasswordField();
        label_noteChangePassword = new javax.swing.JLabel();
        btn_changePassword = new javax.swing.JButton();
        btn_cancelChangePassword = new javax.swing.JButton();
        seperator_changePassword = new javax.swing.JSeparator();
        panel_changeAccountPicture = new javax.swing.JPanel();
        label_changeAccountPictureHeader = new javax.swing.JLabel();
        desktopPane_profPicChangePicture = new javax.swing.JDesktopPane();
        label_DPchangeAccountPicture = new javax.swing.JLabel();
        label_accountNameChangePicture = new javax.swing.JLabel();
        label_accountTypeChangePicture = new javax.swing.JLabel();
        label_passwordDetChangePicture = new javax.swing.JLabel();
        label_noteChangePicture = new javax.swing.JLabel();
        seperator_changeAccountPicture = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        layeredPane_picturesChangePicture = new javax.swing.JLayeredPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        label_browseForMorePictures = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        label_changeAccountNameHeader = new javax.swing.JLabel();
        desktopPane_profPicChangeAccountName = new javax.swing.JDesktopPane();
        label_accountNameChangeAccountName = new javax.swing.JLabel();
        label_accountTypeChangeAccountName = new javax.swing.JLabel();
        label_passwordDetChangeAccountName = new javax.swing.JLabel();
        label_noteChangeAccountName = new javax.swing.JLabel();
        seperator_changeAccountName = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        label_changeAccountName = new javax.swing.JLabel();
        txt_updateAccountName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        label_changeAccountTypeHeader = new javax.swing.JLabel();
        desktopPane_profPicChangeAccountType = new javax.swing.JDesktopPane();
        label_accountNameChangeAccountType = new javax.swing.JLabel();
        label_accountTypeChangeAccountType = new javax.swing.JLabel();
        label_passwordDetChangeAccountType = new javax.swing.JLabel();
        seperator_changeAccountType = new javax.swing.JSeparator();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        radio_cashier = new javax.swing.JRadioButton();
        radio_administrator = new javax.swing.JRadioButton();
        radio_manager = new javax.swing.JRadioButton();
        radio_supervisor = new javax.swing.JRadioButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        label_newAcctype = new javax.swing.JLabel();
        radio_newManager = new javax.swing.JRadioButton();
        txt_newSupervisor = new javax.swing.JRadioButton();
        radio_newCashier = new javax.swing.JRadioButton();
        radio_newAdministrator = new javax.swing.JRadioButton();
        label_newAccName = new javax.swing.JLabel();
        txt_newAccountName = new javax.swing.JTextField();
        btn_newCreateAccount = new javax.swing.JButton();
        label_newCity = new javax.swing.JLabel();
        txt_newFirstName = new javax.swing.JTextField();
        txt_newLastName = new javax.swing.JTextField();
        label_newLastName = new javax.swing.JLabel();
        label_newNic = new javax.swing.JLabel();
        txt_newNic = new javax.swing.JTextField();
        label_newFirstName = new javax.swing.JLabel();
        txt_newCity = new javax.swing.JComboBox();
        label_newWarning = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_deleteAccount = new javax.swing.JTable();
        label_accountNameDeleteAccount = new javax.swing.JLabel();
        label_accountTypeDeleteAccount = new javax.swing.JLabel();
        desktopPane_profPicDeleteAccount = new javax.swing.JDesktopPane();
        label_DPDeleteAccount = new javax.swing.JLabel();
        btn_deleteAccount = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_recoverAccount = new javax.swing.JTable();
        label_accountNameRecoverAccount = new javax.swing.JLabel();
        label_accountTypeRecoverAccount = new javax.swing.JLabel();
        desktopPane_profPicRecoverAccount = new javax.swing.JDesktopPane();
        label_DPRecoverAccount = new javax.swing.JLabel();
        btn_recoverAccount = new javax.swing.JButton();
        btn_cancelManageOtherAccounts = new javax.swing.JButton();
        seperator_manageOtherAccount = new javax.swing.JSeparator();
        btn_userAccount = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Control Panel");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_heading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_heading.setForeground(new java.awt.Color(0, 0, 204));
        label_heading.setText("   Control Panel");
        getContentPane().add(label_heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 780, 10));

        panel_backPanel.setBackground(new java.awt.Color(255, 255, 255));
        panel_backPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_backPanel.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 80, 30));

        getContentPane().add(panel_backPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 790, 35));

        desktopPane_userAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedPane_userAccount.setBackground(new java.awt.Color(255, 255, 255));
        tabbedPane_userAccount.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabbedPane_userAccount.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        panel_userAccountHome.setBackground(new java.awt.Color(255, 255, 255));
        panel_userAccountHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout desktopPane_profPicAccDetLayout = new javax.swing.GroupLayout(desktopPane_profPicAccDet);
        desktopPane_profPicAccDet.setLayout(desktopPane_profPicAccDetLayout);
        desktopPane_profPicAccDetLayout.setHorizontalGroup(
            desktopPane_profPicAccDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        desktopPane_profPicAccDetLayout.setVerticalGroup(
            desktopPane_profPicAccDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_userAccountHome.add(desktopPane_profPicAccDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        label_accountName.setText("Account Name");
        panel_userAccountHome.add(label_accountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 290, 30));

        label_accountType.setText("Account Type");
        panel_userAccountHome.add(label_accountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 290, 30));

        label_passwordDet.setText("Password Det");
        panel_userAccountHome.add(label_passwordDet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 290, 30));

        tabbedPane_userAccount.addTab("Account Details", panel_userAccountHome);

        panel_changeAccountPassword.setBackground(new java.awt.Color(255, 255, 255));
        panel_changeAccountPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout desktopPane_profPicChangePassLayout = new javax.swing.GroupLayout(desktopPane_profPicChangePass);
        desktopPane_profPicChangePass.setLayout(desktopPane_profPicChangePassLayout);
        desktopPane_profPicChangePassLayout.setHorizontalGroup(
            desktopPane_profPicChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        desktopPane_profPicChangePassLayout.setVerticalGroup(
            desktopPane_profPicChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_changeAccountPassword.add(desktopPane_profPicChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        label_accountNameChangePass.setText("Account Name");
        panel_changeAccountPassword.add(label_accountNameChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 290, 30));

        label_accountTypeChangePass.setText("Account Type");
        panel_changeAccountPassword.add(label_accountTypeChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 290, 30));

        label_passwordDetChangePass.setText("Password Det");
        panel_changeAccountPassword.add(label_passwordDetChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 290, 30));

        label_changePasswordHeader.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_changePasswordHeader.setForeground(new java.awt.Color(204, 0, 204));
        label_changePasswordHeader.setText("   Change password");
        panel_changeAccountPassword.add(label_changePasswordHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 30));

        label_currentPassword.setText("Current Password");
        panel_changeAccountPassword.add(label_currentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 130, 30));

        label_newPassword.setText("New Password");
        panel_changeAccountPassword.add(label_newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 130, 30));

        label_confirmPassword.setText("Confirm Password");
        panel_changeAccountPassword.add(label_confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 130, 30));
        panel_changeAccountPassword.add(pass_confirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 260, 30));
        panel_changeAccountPassword.add(pass_currentPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 260, 30));
        panel_changeAccountPassword.add(pass_newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 260, 30));

        label_noteChangePassword.setText("If your password contains capital letters, they must be typed the same way every time you log on.");
        panel_changeAccountPassword.add(label_noteChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 530, 30));

        btn_changePassword.setText("Change Password");
        btn_changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changePasswordActionPerformed(evt);
            }
        });
        panel_changeAccountPassword.add(btn_changePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 150, 30));

        btn_cancelChangePassword.setText("Cancel");
        btn_cancelChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelChangePasswordActionPerformed(evt);
            }
        });
        panel_changeAccountPassword.add(btn_cancelChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 70, 30));
        panel_changeAccountPassword.add(seperator_changePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 640, 10));

        tabbedPane_userAccount.addTab("Change password", panel_changeAccountPassword);

        panel_changeAccountPicture.setBackground(new java.awt.Color(255, 255, 255));
        panel_changeAccountPicture.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_changeAccountPictureHeader.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_changeAccountPictureHeader.setForeground(new java.awt.Color(204, 0, 204));
        label_changeAccountPictureHeader.setText("   Choose a new account picture for your account");
        panel_changeAccountPicture.add(label_changeAccountPictureHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 30));

        javax.swing.GroupLayout desktopPane_profPicChangePictureLayout = new javax.swing.GroupLayout(desktopPane_profPicChangePicture);
        desktopPane_profPicChangePicture.setLayout(desktopPane_profPicChangePictureLayout);
        desktopPane_profPicChangePictureLayout.setHorizontalGroup(
            desktopPane_profPicChangePictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_DPchangeAccountPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        desktopPane_profPicChangePictureLayout.setVerticalGroup(
            desktopPane_profPicChangePictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_DPchangeAccountPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        desktopPane_profPicChangePicture.setLayer(label_DPchangeAccountPicture, javax.swing.JLayeredPane.DEFAULT_LAYER);

        panel_changeAccountPicture.add(desktopPane_profPicChangePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        label_accountNameChangePicture.setText("Account Name");
        panel_changeAccountPicture.add(label_accountNameChangePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 290, 30));

        label_accountTypeChangePicture.setText("Account Type");
        panel_changeAccountPicture.add(label_accountTypeChangePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 290, 30));

        label_passwordDetChangePicture.setText("Password Det");
        panel_changeAccountPicture.add(label_passwordDetChangePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 290, 30));

        label_noteChangePicture.setText("The picture you choose will appear on the Start menu");
        panel_changeAccountPicture.add(label_noteChangePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 530, 30));
        panel_changeAccountPicture.add(seperator_changeAccountPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 640, 10));

        jButton4.setText("Change Picture");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel_changeAccountPicture.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 150, 30));

        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_changeAccountPicture.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 70, 30));

        layeredPane_picturesChangePicture.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        layeredPane_picturesChangePicture.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        layeredPane_picturesChangePicture.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        layeredPane_picturesChangePicture.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        layeredPane_picturesChangePicture.add(jDesktopPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        layeredPane_picturesChangePicture.add(jDesktopPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        panel_changeAccountPicture.add(layeredPane_picturesChangePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 520, 150));

        label_browseForMorePictures.setForeground(new java.awt.Color(0, 0, 204));
        label_browseForMorePictures.setText("Browse for more pictures");
        label_browseForMorePictures.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_browseForMorePicturesMouseClicked(evt);
            }
        });
        panel_changeAccountPicture.add(label_browseForMorePictures, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 170, 30));

        tabbedPane_userAccount.addTab("Change account picture", panel_changeAccountPicture);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_changeAccountNameHeader.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_changeAccountNameHeader.setForeground(new java.awt.Color(204, 0, 204));
        label_changeAccountNameHeader.setText("   Change Account Name");
        jPanel4.add(label_changeAccountNameHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 30));

        javax.swing.GroupLayout desktopPane_profPicChangeAccountNameLayout = new javax.swing.GroupLayout(desktopPane_profPicChangeAccountName);
        desktopPane_profPicChangeAccountName.setLayout(desktopPane_profPicChangeAccountNameLayout);
        desktopPane_profPicChangeAccountNameLayout.setHorizontalGroup(
            desktopPane_profPicChangeAccountNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        desktopPane_profPicChangeAccountNameLayout.setVerticalGroup(
            desktopPane_profPicChangeAccountNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(desktopPane_profPicChangeAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        label_accountNameChangeAccountName.setText("Account Name");
        jPanel4.add(label_accountNameChangeAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 290, 30));

        label_accountTypeChangeAccountName.setText("Account Type");
        jPanel4.add(label_accountTypeChangeAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 290, 30));

        label_passwordDetChangeAccountName.setText("Password Det");
        jPanel4.add(label_passwordDetChangeAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 290, 30));

        label_noteChangeAccountName.setText("This name will appear on the start menu");
        jPanel4.add(label_noteChangeAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 530, 30));
        jPanel4.add(seperator_changeAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 640, 10));

        jButton6.setText("Change Name");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 150, 30));

        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 70, 30));

        label_changeAccountName.setText("New Account Name");
        jPanel4.add(label_changeAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 130, 30));
        jPanel4.add(txt_updateAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 280, 30));

        tabbedPane_userAccount.addTab("Change account name", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_changeAccountTypeHeader.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_changeAccountTypeHeader.setForeground(new java.awt.Color(204, 0, 204));
        label_changeAccountTypeHeader.setText("   Change Account Type");
        jPanel1.add(label_changeAccountTypeHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 30));

        javax.swing.GroupLayout desktopPane_profPicChangeAccountTypeLayout = new javax.swing.GroupLayout(desktopPane_profPicChangeAccountType);
        desktopPane_profPicChangeAccountType.setLayout(desktopPane_profPicChangeAccountTypeLayout);
        desktopPane_profPicChangeAccountTypeLayout.setHorizontalGroup(
            desktopPane_profPicChangeAccountTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        desktopPane_profPicChangeAccountTypeLayout.setVerticalGroup(
            desktopPane_profPicChangeAccountTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(desktopPane_profPicChangeAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        label_accountNameChangeAccountType.setText("Account Name");
        jPanel1.add(label_accountNameChangeAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 290, 30));

        label_accountTypeChangeAccountType.setText("Account Type");
        jPanel1.add(label_accountTypeChangeAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 290, 30));

        label_passwordDetChangeAccountType.setText("Password Det");
        jPanel1.add(label_passwordDetChangeAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 290, 30));
        jPanel1.add(seperator_changeAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 640, 10));

        jButton8.setText("Change Account Type");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 160, 30));

        jButton9.setText("Cancel");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 70, 30));

        buttonGroup1.add(radio_cashier);
        radio_cashier.setText("Cashier");
        jPanel1.add(radio_cashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 80, -1));

        buttonGroup1.add(radio_administrator);
        radio_administrator.setText("Administrator");
        jPanel1.add(radio_administrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        buttonGroup1.add(radio_manager);
        radio_manager.setText("Manager");
        jPanel1.add(radio_manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 80, -1));

        buttonGroup1.add(radio_supervisor);
        radio_supervisor.setText("Supervisor");
        jPanel1.add(radio_supervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 90, -1));

        tabbedPane_userAccount.addTab("Change Account Type", jPanel1);

        jLayeredPane1.setOpaque(true);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_newAcctype.setText("Account Type");
        jLayeredPane2.add(label_newAcctype, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 30));

        buttonGroup2.add(radio_newManager);
        radio_newManager.setText("Manager");
        jLayeredPane2.add(radio_newManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, 30));

        buttonGroup2.add(txt_newSupervisor);
        txt_newSupervisor.setText("Supervisor");
        jLayeredPane2.add(txt_newSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, 30));

        buttonGroup2.add(radio_newCashier);
        radio_newCashier.setText("Cashier");
        jLayeredPane2.add(radio_newCashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, 30));

        buttonGroup2.add(radio_newAdministrator);
        radio_newAdministrator.setText("Administrator");
        jLayeredPane2.add(radio_newAdministrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 30));

        label_newAccName.setText("Account Name");
        jLayeredPane2.add(label_newAccName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 30));
        jLayeredPane2.add(txt_newAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 170, 30));

        btn_newCreateAccount.setText("Create Account");
        btn_newCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newCreateAccountActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btn_newCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 120, 30));

        label_newCity.setText("City");
        jLayeredPane2.add(label_newCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 30));
        jLayeredPane2.add(txt_newFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 170, 30));
        jLayeredPane2.add(txt_newLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 170, 30));

        label_newLastName.setText("Last Name");
        jLayeredPane2.add(label_newLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 80, 30));

        label_newNic.setText("NIC ");
        jLayeredPane2.add(label_newNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 40, 30));
        jLayeredPane2.add(txt_newNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 170, 30));

        label_newFirstName.setText("First Name");
        jLayeredPane2.add(label_newFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 30));

        txt_newCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jLayeredPane2.add(txt_newCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, 30));

        label_newWarning.setText("thjkkkkkkkkkkkkkkkkkkkkkkkkkkkk k kkkkk kkkkkk kkkkk kkkkkkkkk");
        jLayeredPane2.add(label_newWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 54, 450, 20));

        jTabbedPane1.addTab("Create an account", jLayeredPane2);

        jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_deleteAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Select the Account to delete"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_deleteAccount);
        if (table_deleteAccount.getColumnModel().getColumnCount() > 0) {
            table_deleteAccount.getColumnModel().getColumn(0).setResizable(false);
        }

        jLayeredPane3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 240));

        label_accountNameDeleteAccount.setText("Account Name");
        jLayeredPane3.add(label_accountNameDeleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 210, 30));

        label_accountTypeDeleteAccount.setText("Account Type");
        jLayeredPane3.add(label_accountTypeDeleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 210, 30));

        javax.swing.GroupLayout desktopPane_profPicDeleteAccountLayout = new javax.swing.GroupLayout(desktopPane_profPicDeleteAccount);
        desktopPane_profPicDeleteAccount.setLayout(desktopPane_profPicDeleteAccountLayout);
        desktopPane_profPicDeleteAccountLayout.setHorizontalGroup(
            desktopPane_profPicDeleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPane_profPicDeleteAccountLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_DPDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        desktopPane_profPicDeleteAccountLayout.setVerticalGroup(
            desktopPane_profPicDeleteAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPane_profPicDeleteAccountLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_DPDeleteAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        desktopPane_profPicDeleteAccount.setLayer(label_DPDeleteAccount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.add(desktopPane_profPicDeleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        btn_deleteAccount.setText("Delete the account");
        btn_deleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteAccountActionPerformed(evt);
            }
        });
        jLayeredPane3.add(btn_deleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 150, 30));

        jTabbedPane1.addTab("Delete Account", jLayeredPane3);

        jLayeredPane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_recoverAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Deleted Accounts"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_recoverAccount);
        if (table_recoverAccount.getColumnModel().getColumnCount() > 0) {
            table_recoverAccount.getColumnModel().getColumn(0).setResizable(false);
        }

        jLayeredPane4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 240));

        label_accountNameRecoverAccount.setText("Account Name");
        jLayeredPane4.add(label_accountNameRecoverAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 210, 30));

        label_accountTypeRecoverAccount.setText("Account Type");
        jLayeredPane4.add(label_accountTypeRecoverAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 210, 30));

        javax.swing.GroupLayout desktopPane_profPicRecoverAccountLayout = new javax.swing.GroupLayout(desktopPane_profPicRecoverAccount);
        desktopPane_profPicRecoverAccount.setLayout(desktopPane_profPicRecoverAccountLayout);
        desktopPane_profPicRecoverAccountLayout.setHorizontalGroup(
            desktopPane_profPicRecoverAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPane_profPicRecoverAccountLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_DPRecoverAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        desktopPane_profPicRecoverAccountLayout.setVerticalGroup(
            desktopPane_profPicRecoverAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPane_profPicRecoverAccountLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_DPRecoverAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        desktopPane_profPicRecoverAccount.setLayer(label_DPRecoverAccount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.add(desktopPane_profPicRecoverAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        btn_recoverAccount.setText("Recover the account");
        jLayeredPane4.add(btn_recoverAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 150, 30));

        jTabbedPane1.addTab("Recover Account", jLayeredPane4);

        btn_cancelManageOtherAccounts.setText("Cancel");
        btn_cancelManageOtherAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelManageOtherAccountsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(seperator_manageOtherAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelManageOtherAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seperator_manageOtherAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btn_cancelManageOtherAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btn_cancelManageOtherAccounts, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(seperator_manageOtherAccount, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tabbedPane_userAccount.addTab("Manage other accounts", jLayeredPane1);

        desktopPane_userAccount.add(tabbedPane_userAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 790, 480));

        getContentPane().add(desktopPane_userAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 790, 480));

        btn_userAccount.setText("User Account");
        btn_userAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userAccountActionPerformed(evt);
            }
        });
        getContentPane().add(btn_userAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 140, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background/background.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_userAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userAccountActionPerformed
        navigate(desktopPane_userAccount, desktopPane_userAccount, panel_backPanel);
    }//GEN-LAST:event_btn_userAccountActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        BackKey.getInstance().goBack(panel_backPanel);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changePasswordActionPerformed
        actions.actionPassword(new String(pass_currentPass.getPassword()), new String(pass_newPass.getPassword()), new String(pass_confirmPass.getPassword()));
    }//GEN-LAST:event_btn_changePasswordActionPerformed

    private void label_browseForMorePicturesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_browseForMorePicturesMouseClicked
        path = BrowseImage.getInstance().browse(label_DPchangeAccountPicture);
    }//GEN-LAST:event_label_browseForMorePicturesMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        actions.actionPicture(path);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        actions.actionUserName(txt_updateAccountName.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        actions.actionAccType(RadioID.getRadioId(radio_administrator, radio_manager, radio_supervisor, radio_cashier), radio_administrator, radio_cashier, radio_manager, radio_supervisor);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        BackKey.getInstance().goBack(panel_backPanel);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        BackKey.getInstance().goBack(panel_backPanel);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        BackKey.getInstance().goBack(panel_backPanel);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_cancelChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelChangePasswordActionPerformed
        BackKey.getInstance().goBack(panel_backPanel);
    }//GEN-LAST:event_btn_cancelChangePasswordActionPerformed

    private void btn_cancelManageOtherAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelManageOtherAccountsActionPerformed
        BackKey.getInstance().goBack(panel_backPanel);
    }//GEN-LAST:event_btn_cancelManageOtherAccountsActionPerformed

    private void btn_newCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newCreateAccountActionPerformed
        if (label_newWarning.getText().isEmpty()) {
        }
    }//GEN-LAST:event_btn_newCreateAccountActionPerformed

    private void btn_deleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteAccountActionPerformed
        actions.deleteAccount(label_accountNameDeleteAccount.getText());
    }//GEN-LAST:event_btn_deleteAccountActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cancelChangePassword;
    private javax.swing.JButton btn_cancelManageOtherAccounts;
    private javax.swing.JButton btn_changePassword;
    private javax.swing.JButton btn_deleteAccount;
    private javax.swing.JButton btn_newCreateAccount;
    private javax.swing.JButton btn_recoverAccount;
    private javax.swing.JButton btn_userAccount;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JDesktopPane desktopPane_profPicAccDet;
    private javax.swing.JDesktopPane desktopPane_profPicChangeAccountName;
    private javax.swing.JDesktopPane desktopPane_profPicChangeAccountType;
    private javax.swing.JDesktopPane desktopPane_profPicChangePass;
    private javax.swing.JDesktopPane desktopPane_profPicChangePicture;
    private javax.swing.JDesktopPane desktopPane_profPicDeleteAccount;
    private javax.swing.JDesktopPane desktopPane_profPicRecoverAccount;
    private javax.swing.JDesktopPane desktopPane_userAccount;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_DPDeleteAccount;
    private javax.swing.JLabel label_DPRecoverAccount;
    private javax.swing.JLabel label_DPchangeAccountPicture;
    private javax.swing.JLabel label_accountName;
    private javax.swing.JLabel label_accountNameChangeAccountName;
    private javax.swing.JLabel label_accountNameChangeAccountType;
    private javax.swing.JLabel label_accountNameChangePass;
    private javax.swing.JLabel label_accountNameChangePicture;
    private javax.swing.JLabel label_accountNameDeleteAccount;
    private javax.swing.JLabel label_accountNameRecoverAccount;
    private javax.swing.JLabel label_accountType;
    private javax.swing.JLabel label_accountTypeChangeAccountName;
    private javax.swing.JLabel label_accountTypeChangeAccountType;
    private javax.swing.JLabel label_accountTypeChangePass;
    private javax.swing.JLabel label_accountTypeChangePicture;
    private javax.swing.JLabel label_accountTypeDeleteAccount;
    private javax.swing.JLabel label_accountTypeRecoverAccount;
    private javax.swing.JLabel label_browseForMorePictures;
    private javax.swing.JLabel label_changeAccountName;
    private javax.swing.JLabel label_changeAccountNameHeader;
    private javax.swing.JLabel label_changeAccountPictureHeader;
    private javax.swing.JLabel label_changeAccountTypeHeader;
    private javax.swing.JLabel label_changePasswordHeader;
    private javax.swing.JLabel label_confirmPassword;
    private javax.swing.JLabel label_currentPassword;
    private javax.swing.JLabel label_heading;
    private javax.swing.JLabel label_newAccName;
    private javax.swing.JLabel label_newAcctype;
    private javax.swing.JLabel label_newCity;
    private javax.swing.JLabel label_newFirstName;
    private javax.swing.JLabel label_newLastName;
    private javax.swing.JLabel label_newNic;
    private javax.swing.JLabel label_newPassword;
    private javax.swing.JLabel label_newWarning;
    private javax.swing.JLabel label_noteChangeAccountName;
    private javax.swing.JLabel label_noteChangePassword;
    private javax.swing.JLabel label_noteChangePicture;
    private javax.swing.JLabel label_passwordDet;
    private javax.swing.JLabel label_passwordDetChangeAccountName;
    private javax.swing.JLabel label_passwordDetChangeAccountType;
    private javax.swing.JLabel label_passwordDetChangePass;
    private javax.swing.JLabel label_passwordDetChangePicture;
    private javax.swing.JLayeredPane layeredPane_picturesChangePicture;
    private javax.swing.JPanel panel_backPanel;
    private javax.swing.JPanel panel_changeAccountPassword;
    private javax.swing.JPanel panel_changeAccountPicture;
    private javax.swing.JPanel panel_userAccountHome;
    private javax.swing.JPasswordField pass_confirmPass;
    private javax.swing.JPasswordField pass_currentPass;
    private javax.swing.JPasswordField pass_newPass;
    private javax.swing.JRadioButton radio_administrator;
    private javax.swing.JRadioButton radio_cashier;
    private javax.swing.JRadioButton radio_manager;
    private javax.swing.JRadioButton radio_newAdministrator;
    private javax.swing.JRadioButton radio_newCashier;
    private javax.swing.JRadioButton radio_newManager;
    private javax.swing.JRadioButton radio_supervisor;
    private javax.swing.JSeparator seperator_changeAccountName;
    private javax.swing.JSeparator seperator_changeAccountPicture;
    private javax.swing.JSeparator seperator_changeAccountType;
    private javax.swing.JSeparator seperator_changePassword;
    private javax.swing.JSeparator seperator_manageOtherAccount;
    private javax.swing.JTabbedPane tabbedPane_userAccount;
    private javax.swing.JTable table_deleteAccount;
    private javax.swing.JTable table_recoverAccount;
    private javax.swing.JTextField txt_newAccountName;
    private javax.swing.JComboBox txt_newCity;
    private javax.swing.JTextField txt_newFirstName;
    private javax.swing.JTextField txt_newLastName;
    private javax.swing.JTextField txt_newNic;
    private javax.swing.JRadioButton txt_newSupervisor;
    private javax.swing.JTextField txt_updateAccountName;
    // End of variables declaration//GEN-END:variables
    String loginId;
    String path;

    private void onGoingMethods() {
        PanelVisibility.getInstance().visibilityFalse(desktopPane_userAccount, panel_backPanel);
    }

    private void navigate(JDesktopPane currDesktopPane, JComponent... components) {
        PanelVisibility.getInstance().visibilityTrue(currDesktopPane, components);
    }
}
