/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.login;

/**
 *
 * @author Naveen
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        label_alert = new javax.swing.JLabel();
        label_heading = new javax.swing.JLabel();
        label_accName = new javax.swing.JLabel();
        txt_accountName = new javax.swing.JTextField();
        label_nic = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        label_firstName = new javax.swing.JLabel();
        txt_firstName = new javax.swing.JTextField();
        label_lastName = new javax.swing.JLabel();
        txt_lastName = new javax.swing.JTextField();
        label_city = new javax.swing.JLabel();
        txt_city = new javax.swing.JComboBox();
        btn_createAccount = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        label_role = new javax.swing.JLabel();
        combo_role = new javax.swing.JComboBox();
        button_cancel = new javax.swing.JButton();
        label_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("You can customise other settings later");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 620, 20));

        label_alert.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_alert.setText("By default you are the administrator");
        jLayeredPane1.add(label_alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 620, 30));

        label_heading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_heading.setText("Signup to Neelagiri");
        jLayeredPane1.add(label_heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 40));

        label_accName.setText("Account Name");
        jLayeredPane1.add(label_accName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 90, 30));
        jLayeredPane1.add(txt_accountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 170, 30));

        label_nic.setText("NIC ");
        jLayeredPane1.add(label_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 40, 30));
        jLayeredPane1.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 170, 30));

        label_firstName.setText("First Name");
        jLayeredPane1.add(label_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));
        jLayeredPane1.add(txt_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 170, 30));

        label_lastName.setText("Last Name");
        jLayeredPane1.add(label_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 80, 30));
        jLayeredPane1.add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 170, 30));

        label_city.setText("City");
        jLayeredPane1.add(label_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 30));

        txt_city.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jLayeredPane1.add(txt_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 160, 30));

        btn_createAccount.setBackground(new java.awt.Color(0, 0, 204));
        btn_createAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_createAccount.setForeground(new java.awt.Color(255, 255, 255));
        btn_createAccount.setText("Create Account");
        btn_createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createAccountActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btn_createAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 310, 30));
        jLayeredPane1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 620, 20));

        label_role.setText("Role");
        jLayeredPane1.add(label_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 90, 30));

        combo_role.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jLayeredPane1.add(combo_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 160, 30));

        button_cancel.setBackground(new java.awt.Color(153, 0, 0));
        button_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_cancel.setForeground(new java.awt.Color(255, 255, 255));
        button_cancel.setText("Cancel");
        jLayeredPane1.add(button_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 210, 30));
        jLayeredPane1.add(label_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createAccountActionPerformed
      
    }//GEN-LAST:event_btn_createAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_createAccount;
    private javax.swing.JButton button_cancel;
    private javax.swing.JComboBox combo_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_accName;
    private javax.swing.JLabel label_alert;
    private javax.swing.JLabel label_bg;
    private javax.swing.JLabel label_city;
    private javax.swing.JLabel label_firstName;
    private javax.swing.JLabel label_heading;
    private javax.swing.JLabel label_lastName;
    private javax.swing.JLabel label_nic;
    private javax.swing.JLabel label_role;
    private javax.swing.JTextField txt_accountName;
    private javax.swing.JComboBox txt_city;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_nic;
    // End of variables declaration//GEN-END:variables
}
