/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.login;

/**
 *
 * @author Naveen
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        label_alert = new javax.swing.JLabel();
        label_heading = new javax.swing.JLabel();
        label_newAccName = new javax.swing.JLabel();
        txt_newAccountName = new javax.swing.JTextField();
        label_newNic = new javax.swing.JLabel();
        txt_newNic = new javax.swing.JTextField();
        label_newFirstName = new javax.swing.JLabel();
        txt_newFirstName = new javax.swing.JTextField();
        label_newLastName = new javax.swing.JLabel();
        txt_newLastName = new javax.swing.JTextField();
        label_newCity = new javax.swing.JLabel();
        txt_newCity = new javax.swing.JComboBox();
        btn_newCreateAccount = new javax.swing.JButton();
        label_bg = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("You can customise other settings later");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 254, 620, 20));

        label_alert.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_alert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_alert.setText("By default you are the administrator");
        jLayeredPane1.add(label_alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 620, 30));

        label_heading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_heading.setText("Signup to Neelagiri");
        jLayeredPane1.add(label_heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 40));

        label_newAccName.setText("Account Name");
        jLayeredPane1.add(label_newAccName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 90, 30));
        jLayeredPane1.add(txt_newAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 170, 30));

        label_newNic.setText("NIC ");
        jLayeredPane1.add(label_newNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 40, 30));
        jLayeredPane1.add(txt_newNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 170, 30));

        label_newFirstName.setText("First Name");
        jLayeredPane1.add(label_newFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 30));
        jLayeredPane1.add(txt_newFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 170, 30));

        label_newLastName.setText("Last Name");
        jLayeredPane1.add(label_newLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 80, 30));
        jLayeredPane1.add(txt_newLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 170, 30));

        label_newCity.setText("City");
        jLayeredPane1.add(label_newCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 30));

        txt_newCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jLayeredPane1.add(txt_newCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 160, 30));

        btn_newCreateAccount.setBackground(new java.awt.Color(0, 0, 204));
        btn_newCreateAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_newCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        btn_newCreateAccount.setText("Create Account");
        btn_newCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newCreateAccountActionPerformed(evt);
            }
        });
        jLayeredPane1.add(btn_newCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 250, 30));
        jLayeredPane1.add(label_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 280));
        jLayeredPane1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 620, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newCreateAccountActionPerformed
      
    }//GEN-LAST:event_btn_newCreateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_newCreateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_alert;
    private javax.swing.JLabel label_bg;
    private javax.swing.JLabel label_heading;
    private javax.swing.JLabel label_newAccName;
    private javax.swing.JLabel label_newCity;
    private javax.swing.JLabel label_newFirstName;
    private javax.swing.JLabel label_newLastName;
    private javax.swing.JLabel label_newNic;
    private javax.swing.JTextField txt_newAccountName;
    private javax.swing.JComboBox txt_newCity;
    private javax.swing.JTextField txt_newFirstName;
    private javax.swing.JTextField txt_newLastName;
    private javax.swing.JTextField txt_newNic;
    // End of variables declaration//GEN-END:variables
}
