/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.invoice;

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akash
 */
public class Invoice extends javax.swing.JInternalFrame {

    private static Invoice VInvoice;

    /**
     * Creates new form Invoice
     */
    private Invoice() {
        initComponents();
        lab_treater.setVisible(false);
        Radio_normalBill.setSelected(true);
    }

    public static Invoice getInstance() {
        if (VInvoice == null) {
            VInvoice = new Invoice();
        }
        return VInvoice;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BTN_Table_add = new javax.swing.JButton();
        txt_waiterID = new javax.swing.JTextField();
        txt_qty = new javax.swing.JTextField();
        txt_proID = new javax.swing.JTextField();
        Lab_proID = new javax.swing.JLabel();
        lab_qty = new javax.swing.JLabel();
        lab_witerID = new javax.swing.JLabel();
        lab_treater = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Radio_treatBill = new javax.swing.JRadioButton();
        Radio_normalBill = new javax.swing.JRadioButton();
        lab_tot = new javax.swing.JLabel();
        lab_total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Invoice");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_Table_add.setText("jButton1");
        BTN_Table_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_Table_addActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_Table_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, -1, -1));
        getContentPane().add(txt_waiterID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 150, -1));
        getContentPane().add(txt_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 150, -1));
        getContentPane().add(txt_proID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 150, -1));

        Lab_proID.setText("Procut ID :");
        getContentPane().add(Lab_proID, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 70, 20));

        lab_qty.setText("Quantity :");
        getContentPane().add(lab_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 60, 20));

        lab_witerID.setText("Waiter ID :");
        getContentPane().add(lab_witerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 20));

        lab_treater.setText("Treater ID :");
        getContentPane().add(lab_treater, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Unite Price", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 600, 260));

        buttonGroup1.add(Radio_treatBill);
        Radio_treatBill.setText("Treat Bill");
        Radio_treatBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_treatBillActionPerformed(evt);
            }
        });
        getContentPane().add(Radio_treatBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        buttonGroup1.add(Radio_normalBill);
        Radio_normalBill.setText("Normal Bill");
        Radio_normalBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_normalBillActionPerformed(evt);
            }
        });
        getContentPane().add(Radio_normalBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        lab_tot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lab_tot.setText("Total :");
        getContentPane().add(lab_tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 60, 40));

        lab_total.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lab_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_total.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lab_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 150, 40));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 110, 70));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 750, 60));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 250, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Radio_treatBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_treatBillActionPerformed
        lab_treater.setVisible(true);
        lab_witerID.setVisible(false);
    }//GEN-LAST:event_Radio_treatBillActionPerformed

    private void Radio_normalBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_normalBillActionPerformed
        lab_treater.setVisible(false);
        lab_witerID.setVisible(true);
    }//GEN-LAST:event_Radio_normalBillActionPerformed
    /* <<<<<<< HEAD =======>>>>>>> 0d2e4b68541702dae1913beaf14aba2ba3eeb19e */

    private void BTN_Table_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Table_addActionPerformed

        try {
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            Vector v = new Vector();
            
            v.add(txt_proID.getText());
            v.add(txt_qty.getText());
            dt.addRow(v);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BTN_Table_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Table_add;
    private javax.swing.JLabel Lab_proID;
    private javax.swing.JRadioButton Radio_normalBill;
    private javax.swing.JRadioButton Radio_treatBill;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lab_qty;
    private javax.swing.JLabel lab_tot;
    private javax.swing.JLabel lab_total;
    private javax.swing.JLabel lab_treater;
    private javax.swing.JLabel lab_witerID;
    private javax.swing.JTextField txt_proID;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_waiterID;
    // End of variables declaration//GEN-END:variables
}
